//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiziqFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiziqFinalEntities : DbContext
    {
        public RiziqFinalEntities()
            : base("name=RiziqFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BlogPost> BlogPosts { get; set; }
        public DbSet<NeedHelp> NeedHelps { get; set; }
        public DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public DbSet<TBL_DONATE> TBL_DONATE { get; set; }
        public DbSet<TBL_DONATEOthers> TBL_DONATEOthers { get; set; }
        public DbSet<TBL_FEEDBACK> TBL_FEEDBACK { get; set; }
        public DbSet<TBL_MEMBERSHIP> TBL_MEMBERSHIP { get; set; }
        public DbSet<TBL_NEEDTYPE> TBL_NEEDTYPE { get; set; }
        public DbSet<TBL_OCCUPATION> TBL_OCCUPATION { get; set; }
        public DbSet<TBL_USER> TBL_USER { get; set; }
    }
}
