//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiziqFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeedHelp
    {
        public int N_id { get; set; }
        public string N_Name { get; set; }
        public string N_Email { get; set; }
        public string N_contact { get; set; }
        public string N_Address { get; set; }
        public Nullable<int> HelpType { get; set; }
        public string Bkash { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
        public Nullable<int> N_status { get; set; }
    
        public virtual TBL_NEEDTYPE TBL_NEEDTYPE { get; set; }
    }
}
