//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiziqFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_email { get; set; }
        public Nullable<int> u_occupation { get; set; }
        public string u_contact { get; set; }
        public string u_password { get; set; }
        public string u_cpassword { get; set; }
        public Nullable<int> u_type { get; set; }
        public Nullable<int> u_status { get; set; }
    
        public virtual TBL_MEMBERSHIP TBL_MEMBERSHIP { get; set; }
        public virtual TBL_OCCUPATION TBL_OCCUPATION { get; set; }
    }
}
