//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiziqFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DONATE
    {
        public int d_id { get; set; }
        public string d_name { get; set; }
        public string d_cardname { get; set; }
        public string d_cardnumber { get; set; }
        public Nullable<System.DateTime> d_validdate { get; set; }
        public Nullable<System.DateTime> d_expiredate { get; set; }
        public string d_securitycode { get; set; }
        public string d_email { get; set; }
        public string d_address { get; set; }
        public string d_contact { get; set; }
        public string d_country { get; set; }
        public string d_postcode { get; set; }
        public string d_amount { get; set; }
    }
}
