//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiziqFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DONATEOthers
    {
        public int do_id { get; set; }
        public string do_name { get; set; }
        public string do_email { get; set; }
        public string do_contact { get; set; }
        public string do_address { get; set; }
        public string do_ImagePath { get; set; }
        public Nullable<int> do_HelpType { get; set; }
        public int do_Quantity { get; set; }
        public string do_Description { get; set; }
        public Nullable<int> DO_status { get; set; }
    
        public virtual TBL_NEEDTYPE TBL_NEEDTYPE { get; set; }
    }
}
